export const deliveryCriteria = [
  "The Missions Delivery panel links the native plan and shows its bound revision.",
  "Accepted candidate and PR follow the backend N5 readback; divergent head invalidates readiness without erasing history.",
  "Missing authority, unknown publication, absent/pending/failed checks show the reason and next actor, never ready.",
  "Distinguish draft, open and ready PR with a correct link; technical details stay secondary to useful actions.",
  "Backend projection/tests and frontend contributions, integration, N3 opinions, independent acceptance and publisher run are attributable.",
  "Observe the integrated candidate UI in a browser; link the actual PR to that exact accepted candidate. Correct only a real material finding.",
];
export const deliveryWork = [
  { key: "backend", title: "Delivery presentation contract and tests", ownedPaths: ["src/delivery-presentation.ts", "tests/delivery-presentation.spec.ts"],
    instruction: "Produce a pure presentation projection from existing N5 inspection: priority status, waiting reason, next action, useful references. Preserve every publication/acceptance authority rule. Own only the declared backend/test paths." },
  { key: "frontend", title: "Missions Delivery panel", ownedPaths: ["src/ui/index.tsx"],
    instruction: "Add the useful Delivery panel to CouncilMissionsPage, consuming the backend presentation contract. Link plan/PR and show unknown/pending/mismatch states accessibly. Never infer readiness from URL alone. Own only the frontend path." },
];
export function n45Instructions(role: string, profile: any) {
  const common = `You participate in the Council Delivery mission. Read your native task, current plan and exact candidate before acting. No provider retry, no new agent, no secrets in output. Unknown effects stay unknown; inspect before recovery. Do not modify G3/G4, host/core, dependencies, or unowned paths. Generate each command UUID with node:crypto.randomUUID().\n\nPlugins/skills à utiliser\nUse only the Paperclip instructions/tools injected by this host, then the existing Council command contract in the task and docs/n5/NATIVE-DELIVERY.md. Do not assume this human Codex plugin catalogue is installed in your agent.\n\nModele et effort recommandes\nTarget: ${role}. Requested campaign model ${profile.model}, effort ${profile.effort}; recommendation gpt-5.6-sol/medium for bounded implementation/review. Source /home/davy-lp/.codex/shared/model-selection/model-effort-mapping.md dated2026-09-05. Effective availability remains unobserved until runtime. Re-evaluate only on substantive difficulty or unsupported configuration; never silently substitute.`;
  const roles: Record<string, string> = {
    lead: "You carry planning, orchestration, integration and later publication in distinct admitted runs. During N1, inspect the source, refine the native plan with baseRevisionId, establish the presentation interface, plan/materialize the two declared contributions, then dispatch and settle backend before frontend. Your N1 run remains occupied and counted during child execution: use one bounded terminal polling script per child, never repeated model turns to poll. Integrate their commits and run canonical checks. Produce a self-contained Git bundle refs/heads/base and refs/heads/candidate, upload it, then publish through existing N1 commands. Finish N1 ready_for_review; owner settles and switches your adapter. Before the final N2/N3 review handoff the owner must hold your dedicated lead timer and demand wakes after any required N3 bridge has started; do not finish the handoff before that readback. During native N2 root runs inspect Council first: attest-transmission or attest-n3-transmission as appropriate, then request independent native review; never accept your work. During a released correction change only the justified owned paths, rebind the plan if needed and use prepare-resubmission; do not reset history. During a publisher child inspect/claim N5 before the one permitted git/gh effect; verify repository/base/head/exact accepted SHA. Operation update targets the SAME PR. Write attributed work-product and delivery document, refresh native object, then observe. On refresh backoff or pending CI finish and leave owner readback; no idle model polling. Do not merge.",
    backend: deliveryWork[0]!.instruction + " Read the plan interface, commit your contribution and record-contribution using exact native issue/run identity. Mark done only after the Council command succeeds. Git local only; no GitHub operation.",
    frontend: deliveryWork[1]!.instruction + " Read the backend contribution first, commit your contribution and record-contribution. Mark done only after success. Git local only; no GitHub operation.",
    development: "You advise on implementation correctness, interface fit and scope. Use n3-inspect and n3-opinion on your exact child; bind every claim to the provided subject/candidate and evidence. Do not edit source or decide the root. Preserve honest evidence limits.",
    quality: "You independently assess readiness states, regressions and validation evidence including accessible UI states. Use n3-inspect/n3-opinion on your exact child and subject. Do not edit source or decide the root. Require actual observations; do not invent a defect to exercise correction.",
    reviewer: "You alone own the independent native verdict. Use get_task_context, get_task_history and native read_document tools to inspect the one active Council review packet, exact candidate evidence and N3 opinions. Copy packetHash and subject from its JSON example unchanged; invent no identifiers. Resolve the assigned native review with resolve_review {decision: accept|reject, reason on reject}. Finish with summary containing ONLY the packet's JSON report format: schema, packetHash, subject, verdict approved|changes_requested, rationale, dispositions for every material objection. Never call Council APIs or use another actor credential. Your native verdict and terminal summary are read back by Council; publication and dependent Council work wait for exact candidate/opinions/attribution/cost validation. Reject only a real material defect; maxCorrections1 remains binding.",
  };
  return roles[role] + "\n\n" + common;
}
