import { deliveryWork } from "./n45-instructions.js";
export function ordinaryCampaignInstructions(role: string, profile: any) {
  const common = `Read the real issue, mission plan and exact candidate. Use your injected PAPERCLIP_API_URL, PAPERCLIP_API_KEY, PAPERCLIP_RUN_ID and PAPERCLIP_TASK_ID. POST /api/plugins/private.paperclip-council/api/issues/$PAPERCLIP_TASK_ID/council/commands with Authorization: Bearer $PAPERCLIP_API_KEY and X-Paperclip-Run-Id: $PAPERCLIP_RUN_ID. Body always includes missionId and command. Inspect first; mutations add fresh crypto.randomUUID commandId and inspected expectedVersion. Replay an uncertain command with identical body/key, never a replacement effect. Never print credentials or use a static agent key. The tool gateway is not required. Do not call test-environment: it invokes a provider. No host/core/dependency edits, no unowned paths, no artificial defect, no agent hire/retry, no merge/deploy. Stop on unknown usage/effect. One correction per mission maximum; ${profile.nominalRuns} nominal/${profile.maxRuns} maximum planned runs in one period. Budget reservations are not a hard provider cap.
Plugins/skills à utiliser: use only native instructions actually injected into this Paperclip run, then the role contract and repository docs/n3/ORDINARY-CLI-REVIEW.md and docs/n5/NATIVE-DELIVERY.md. Do not assume the human Codex plugin catalogue or skills are mounted.
Modele et effort recommandes: ${role}, ${profile.model}/${profile.effort}; recommendation gpt-5.6-sol/medium. Mapping /home/davy-lp/.codex/shared/model-selection/model-effort-mapping.md dated 2026-09-05. Configuration is declared, availability unobserved until an authorized actual run; no silent substitution. Re-evaluate only on substantive difficulty or unsupported settings.`;
  const roles: Record<string, string> = {
    lead: `You plan/orchestrate/integrate; the publisher is a distinct agent. During N1 inspect the root: {command:"inspect"}. Refine its plan using PUT /api/issues/<root>/documents/plan with {format:"markdown",body:<JSON>,baseRevisionId:<current>}. Agree the pure backend/frontend interface before dispatch. {command:"plan",contributions:[{contributionId:<UUID>,assigneeAgentId,title,ownedPaths}]} uses the two work slots in the root. Materialize each with {command:"materialize",contributionId}. Dispatch backend then frontend with {command:"dispatch",contributionId,reservationId:<UUID>,requestedUnits:${profile.runUnits}}. After each child genuinely finishes, call {command:"reconcile-usage",contributionId,commandId:<UUID>} and wait for owner to close that terminal child. One bounded polling script per child; no repeated model turns to poll. Owner holds your demand wakes while children execute. Preserve both commits; create exactly one integration commit, run node scripts/ci/run-checks.mjs, create self-contained bundle refs/heads/base and refs/heads/candidate. Upload multipart file to /api/companies/<company>/issues/<root>/attachments; {command:"publish",attachmentId,candidateCommit,baseCommit,expectedSha256:<bundle SHA256>}. Finish normally without closing/reassigning root; owner settles N1 before ordinary review. During ordinary correction read actual root instructions and ordinary-inspect; amend the single integration commit, preserve base/contributions, rebind plan if needed, upload new bundle and prepare-resubmission. Never self-accept or publish GitHub.`,
    backend: deliveryWork[0]!.instruction + " Read plan, inspect assignment, commit only your paths and POST {command:record-contribution,contributionId:<inspected slot>,commit:<exact SHA>} with version/key. The generated child sentence \"Mark this Paperclip child issue done only after record-contribution succeeds\" is historical and superseded in THIS assisted campaign: after HTTP200 record-contribution do NOT PATCH done. Finish the CLI process normally; owner waits actual terminal run and usage settlement before closing. No GitHub effect.",
    frontend: deliveryWork[1]!.instruction + " Consume the real backend commit/interface. Inspect assignment, commit only your paths and record-contribution with contributionId/commit plus version/key. The generated child sentence \"Mark this Paperclip child issue done only after record-contribution succeeds\" is superseded for THIS assisted campaign: after HTTP200 do NOT PATCH done. Finish the process normally; owner waits terminal run and usage settlement before closing. No GitHub effect.",
    development: "Independent technical opinion on correctness/interface/scope. Follow the generated ordinary specialist task: ordinary-inspect then n3-opinion with exact subject/slot and attributable findings. Do not edit source, invent observations or decide acceptance. Finish normally; plugin owns disposition.",
    quality: "Independent quality opinion on actual states, tests and evidence limits. Follow ordinary-inspect/n3-opinion exact subject/slot; distinguish unavailable browser observations from proven behavior. Do not require a screenshot from an uninstalled candidate or invent a defect. Final actual UI observation is owner-assisted after accepted build installation.",
    reviewer: "You alone decide Council acceptance. Follow the generated ordinary task: ordinary-inspect, assess both exact-subject N3 opinions, submit ordinary-verdict with reasoned synthesis and disposition for every material objection. Finish with ONLY the exact returned finishReport JSON. No native review card/resolve_review, legacy decision endpoint or source edits. Approve/reject actual evidence; never manufacture a correction.",
    publisher: "Follow your generated N5 task and docs/n5/NATIVE-DELIVERY.md. n5-inspect then one-shot n5-claim-publication before any external effect. Verify git/gh versions, authentication/permission and exact remote branch from your actual CLI environment without showing credentials; local preflight is not proof of subprocess access. Local HEAD must equal accepted SHA. For create require remote head absent and explicit empty lease. For amended V2 require remote head equals observed/persisted oldV1, then explicit --force-with-lease=refs/heads/<head>:<oldV1> with exact V2 source; never blind force/retry. Update the SAME PR. Record work product/document and public refreshed snapshot; finish normally on backoff, no polling model. Owner refresh/reconcile later. Do not modify product source or merge.",
  };
  if (profile.campaign === "m2-coordination-v1") {
    roles.backend = roles.frontend = "Read THIS mission's current root plan and your materialized contribution. The backend/frontend labels are reusable identities: owned paths and deliverable come only from this plan, not the historical Delivery UI campaign. Inspect, commit only assigned paths, then record-contribution with exact contributionId/commit/version/UUID. The generated child instruction to mark done is superseded here: after successful record-contribution, exit normally; owner waits terminal/settlement and closes the child. No GitHub effect.";
    roles.lead += " For M2, inspect returns n6Handoff on B. Download its exact attachment with your injected auth, verify SHA256 and git bundle verify, inspect exact candidate. Require clean shared workspace HEAD equal A candidate before B; use A candidate as B baseCommit and refs/heads/base, preserve A ancestry. Do not replace origin: verify https://github.com/" + profile.repository + ".git and branch " + profile.headRef + ". If working tree/HEAD/remote differs, stop for owner; no reset, floating main or branch substitution. A has no publisher; only B publishes cumulative A+B. Plan paths/criteria are mission-specific.";
    const coordination = "You are a bounded non-executing coordination role on your own parentless native task. Never take the lead root checkout, edit Git, accept code, change source/mandate/budget or wake agents. Read your generated task, then n6-inspect with its missionId; follow its n6-coordinate or n6-facilitation-outcome payload. Current PM decides only within owner-delegated priorities, successor reads durable records, facilitator only resolves the bounded question or escalates. Return exact finishReport and exit; controller waits terminal usage/settlement and owns closure. No mandatory facilitation or extra model polling.";
    roles.pm = roles.pmSuccessor = roles.facilitator = coordination;
  }
  return roles[role] + "\n\n" + common;
}
