import { fileURLToPath } from "node:url";
import type { MissionRecord } from "./missions.js";

export function integrationInstructions(m: MissionRecord) {
  const path = fileURLToPath(new URL("../scripts/operations/github_integration.py", import.meta.url));
  const command = fileURLToPath(new URL("../scripts/operations/integrate_delivery.py", import.meta.url));
  return `Run the guarded executable first: python3 ${JSON.stringify(command)} merge --mission-id ${m.missionId} --company-id ${m.companyId}, in the admitted repository. It persists 0600 intents before native/GitHub effects, pins the candidate in the GitHub merge request, and handles the bounded native claim wait below before polling readbacks within this run (at most ten observations, 30-second intervals). Respect the earlier native run timeout/deadline; pending CI stops with the same intent. On any lost/unknown reply or interruption, use the same script with operation observe; a prepared/claimed merge can never be repeated. Never reconstruct a second gh merge request manually.
Council integrated delivery ${m.missionId}. This is the separately reserved publisher run for the already existing PR. No new PR, push, branch deletion or deployment is authorized.
Use the injected native Bearer credentials and X-Paperclip-Run-Id only at POST /api/plugins/private.paperclip-council/api/issues/$PAPERCLIP_TASK_ID/council/commands. Start with {command:"n5-inspect",missionId:"${m.missionId}"}. Pin delivery.publication.targetUrl, submission and authority from inspection.
Run the read-only Python helper ${JSON.stringify(path)} with argv --url <targetUrl> --repository <authority.repository> --head <candidateCommit> --base-ref <authority.baseRef> --base-sha <submission.baseCommit> --company-id ${m.companyId} --mission-id ${m.missionId} --intent-id <publication.intentId>. It inherits the existing publisher GitHub environment. Obtain a fresh github_feedback.py report for the same intent, head and native actor. Before merge, refresh the ORIGINAL publication issue's native external object, respecting its refresh backoff. No operator credential is permitted.
The guarded executable performs these steps internally (do not execute them a second time). It inspects again and posts {command:"n5-claim-merge",missionId:"${m.missionId}",commandId:<crypto.randomUUID>,expectedVersion:<fresh version>,integrationReport:<helper JSON>,feedbackReport:<feedback JSON>}. Journal the exact payload/key in a 0600 file inside the Git directory BEFORE sending. Only HTTP 200 and effectPermission=execute authorize one merge. Only an explicit HTTP 409 linear_continuity_source_pending or linear_continuity_publication_pending permits waiting inside this executable: at most six identical POSTs in 30 seconds, five seconds apart, under the original source exchange budget. The commandId, expectedVersion and reports stay unchanged; no model polling or new run is needed. Every other refusal, missing/lost response, timeout, replay, pending checks/review or changed head stops all writes and retains the original intent. An exhausted wait never permits restarting merge with its prepared journal.
It uses a fixed argv subprocess for gh api --method PUT repos/<repository>/pulls/<exact PR number>/merge --input <0600 JSON file>, whose body is {sha:<exact accepted candidateCommit>,merge_method:<explicit integration.mergeMethod>}. Never use an auto-merge queue, administrator bypass, changed SHA or a second merge request. Preserve branch protection. A lost merge response permits only readback of this same PR.
The executable observes the same merge with fresh version/key and integrationReport. For later readback, run the executable with operation observe. Pending/failed post-merge checks keep the next delivery blocked. Do not report passed from candidate checks: only checks on integratedCommit count. A correction/rollback requires a separately authorized PR and independent review; this run never rewrites an integrated result. Finish the admitted run; Council retains known terminal accounting through its existing driver. Do not mark the product task done or wake another actor.
Plugins/skills à utiliser: existing Council integration contract, then repository Git/GitHub instructions. Modèle et effort recommandés: publisher using the mission's pinned orchestration profile; effective model/effort are observed in the native launch. The prescribed repository/home model-selection mapping was unavailable during authoring (2026-10-09); no alternate mapping or supported option is inferred.`;
}
