import { MODEL_PROFILE_MAPPING_SCHEMA, managedAgentDeclarations, managedSkillDeclarations } from "./model-catalogue.js";
import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";

export const PLUGIN_ID = "private.paperclip-council";

export const missionToolDeclaration = {
  name: "mission-command", displayName: "Council mission command",
  description: "Execute an existing Council agent command or independent decision for this exact active native run. Owner commands are unavailable.",
  parametersSchema: { type: "object", additionalProperties: false, required: ["operation", "body"], properties: {
    operation: { type: "string", enum: ["command", "decision"] }, body: { type: "object", additionalProperties: true } } },
};

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: "0.7.17",
  displayName: "Paperclip Council",
  description: "Private Council integration with revisioned rosters, bounded admission and checked candidate preparation.",
  author: "Local Paperclip integration",
  categories: ["automation"],
  capabilities: [
    "api.routes.register",
    "agent.tools.register",
    "companies.read",
    "projects.read",
    "agents.read",
    "agents.managed",
    "skills.managed",
    "issue.comments.read",
    "issue.comments.create",
    "issue.documents.write",
    "database.namespace.migrate",
    "database.namespace.read",
    "database.namespace.write",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.checkout",
    "issues.wakeup",
    "issue.relations.read",
    "issue.relations.write",
    "issues.orchestration.read",
    "events.subscribe",
    "events.emit",
    "jobs.schedule",
    "plugin.state.read",
    "plugin.state.write",
    "issue.documents.read",
    "issue.attachments.read",
    "issue.interactions.create",
    "issue.interactions.read",
    "issue.interactions.respond",
    "secrets.read-ref",
    "ui.page.register",
  ],
  agents: managedAgentDeclarations(),
  skills: managedSkillDeclarations(),
  tools: [missionToolDeclaration],
  jobs: [{ jobKey: "mission-continuity", displayName: "Council mission continuity",
    description: "Reconcile explicitly delegated ordinary missions without another model turn or chat watcher.", schedule: "* * * * *" }],
  entrypoints: { worker: "./dist/worker.js", ui: "./dist/ui" },
  database: {
    namespaceSlug: "private_paperclip_council",
    migrationsDir: "migrations",
    coreReadTables: ["companies", "issues", "projects"],
  },
  instanceConfigSchema: {
    type: "object",
    additionalProperties: false,
    required: ["apiBaseUrl", "councilAgentId", "councilApiKey"],
    properties: {
      modelVariantsEnabled: { type: "boolean", default: false, description: "Use prepared fixed-profile Council variants on newly created standard missions only." },
      nativeWakeGuardEnabled: { type: "boolean", default: true, description: "Pin Council-owned N1 child completion and blocked root waiting on new ordinary missions. Preserve historical contracts; never disable agent demand wakes." },
      nativeRunLimit: { type: "integer", minimum: 1, maximum: 256, description: "Optional explicit total observed native run limit, pinned on new ordinary missions. Includes governed repeats and unexpected runs; no limit is invented when absent. Not a provider token ceiling." },
      n5PublisherPreflightEnabled: { type: "boolean", default: true, description: "Require a fresh attributed read-only Git/GitHub report inside the already admitted publisher run before claiming a publication write. Pinned on new ordinary N5 authorizations; historical authorities are preserved." },
      workspacePreflight: { type: "object", additionalProperties: false, required: ["codexHome"],
        description: "Opt in new fixed-variant ordinary missions to provider-free Git sandbox checks. Register the observed effective native Codex home; historical missions retain their pinned configuration. This is not proof of GitHub access or model execution.",
        properties: { codexHome: { type: "string", minLength: 1 }, codexCommand: { type: "string", minLength: 1 }, sandboxHelper: { type: "string", minLength: 1 } } },
      modelProfileMapping: { ...MODEL_PROFILE_MAPPING_SCHEMA,
        description: "Versioned family/profile catalogue. Shared runtime validation applies before selection; existing tasks retain their snapshot." },
      apiBaseUrl: {
        type: "string",
        format: "uri",
        title: "Paperclip API base URL",
        description: "Loopback origin of the Paperclip instance, without credentials, path, query, fragment, or an /api suffix.",
      },
      councilAgentId: {
        type: "string",
        format: "uuid",
        title: "Council agent ID",
        description: "Paperclip agent whose dedicated standard API key is stored below.",
      },
      councilApiKey: {
        format: "secret-ref",
        title: "Council agent API key",
        description: "Reference to the Paperclip company secret containing the dedicated council agent token.",
      },
      n2RuntimeProfile: {
        type: "string", enum: ["ordinary-cli-v1", "paperclip_runner-experimental"],
        description: "Select ordinary-cli-v1 for new reviews: separate N3 specialist and Council CLI tasks with terminal accounting. Existing missions retain their persisted runtime; paperclip_runner-experimental remains available for historical native missions.",
      },
      n1FixtureMode: {
        type: "string",
        enum: ["ephemeral-local-sandbox"],
        title: "N1 test fixture mode",
        description: "Only for the repo-owned ephemeral test host; real admission remains unqualified.",
      },
      n1OperatingProfile: {
        type: "object",
        additionalProperties: false,
        required: [
          "kind", "periodKey", "periodStart", "periodEnd", "periodAllowanceUnits", "runReservationUnits",
          "initialKnownUsageUnits", "initialExposureUnits", "initialTokenAccountingSource",
        ],
        title: "N1 bounded operating profile",
        description: "One native token-ledger profile for sequential N1 contribution runs and an explicitly bounded N2 correction.",
        properties: {
          kind: { type: "string", enum: ["paperclip-orchestration-tokens-v1"] },
          periodKey: { type: "string", minLength: 1, maxLength: 200 },
          periodStart: { type: "string", format: "date-time" },
          periodEnd: { type: "string", format: "date-time" },
          periodAllowanceUnits: { type: "integer", minimum: 1 },
          runReservationUnits: { type: "integer", minimum: 1 },
          initialKnownUsageUnits: { type: "integer", minimum: 0 },
          initialExposureUnits: { type: "integer", minimum: 0 },
          initialTokenAccountingSource: { type: "string", minLength: 1, maxLength: 200 },
          maxCorrections: { type: "integer", enum: [0, 1], default: 0 },
        },
      },
    },
  },
  apiRoutes: [
    { routeKey: "project-mandate-read", method: "GET", path: "/companies/:companyId/projects/:projectId/mandate", auth: "board",
      capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "project-mandate-command", method: "POST", path: "/companies/:companyId/projects/:projectId/mandate", auth: "board",
      capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "model-profiles-read", method: "GET", path: "/companies/:companyId/model-profiles", auth: "board",
      capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "model-profiles-command", method: "POST", path: "/companies/:companyId/model-profiles", auth: "board",
      capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "model-selection-read", method: "GET", path: "/companies/:companyId/missions/:missionId/model-profiles", auth: "board",
      capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    {
      routeKey: "admission-read",
      method: "GET",
      path: "/companies/:companyId/admission",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "admission-command",
      method: "POST",
      path: "/companies/:companyId/admission",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "mission-agent-command",
      method: "POST",
      path: "/issues/:issueId/council/commands",
      auth: "agent",
      capability: "api.routes.register",
      checkoutPolicy: "required-for-agent-in-progress",
      companyResolution: { from: "issue", param: "issueId" },
    },
    {
      routeKey: "rosters-list",
      method: "GET",
      path: "/companies/:companyId/rosters",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "rosters-command",
      method: "POST",
      path: "/companies/:companyId/rosters",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "roster-read",
      method: "GET",
      path: "/companies/:companyId/rosters/:rosterId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "roster-command",
      method: "POST",
      path: "/companies/:companyId/rosters/:rosterId/commands",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "missions-list",
      method: "GET",
      path: "/companies/:companyId/missions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "missions-command",
      method: "POST",
      path: "/companies/:companyId/missions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "mission-read",
      method: "GET",
      path: "/companies/:companyId/missions/:missionId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "mission-command",
      method: "POST",
      path: "/companies/:companyId/missions/:missionId/commands",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "decision",
      method: "POST",
      path: "/issues/:issueId/decision",
      auth: "agent",
      capability: "api.routes.register",
      checkoutPolicy: "required-for-agent-in-progress",
      companyResolution: { from: "issue", param: "issueId" },
    },
    {
      routeKey: "council-decisions-list",
      method: "GET",
      path: "/companies/:companyId/decisions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "council-decision-human",
      method: "POST",
      path: "/companies/:companyId/decisions/human",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "foundation-probe",
      method: "POST",
      path: "/issues/:issueId/foundation-probe",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "issue", param: "issueId" },
    },
  ],
  ui: {
    slots: [{
      type: "page",
      id: "council-rosters",
      displayName: "Council rosters",
      exportName: "CouncilRostersPage",
      routePath: "council-rosters",
    }, {
      type: "page",
      id: "council-missions",
      displayName: "Council missions",
      exportName: "CouncilMissionsPage",
      routePath: "council-missions",
    }],
  },
};

export default manifest;
