import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";

export const PLUGIN_ID = "private.paperclip-council";

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: "0.5.0",
  displayName: "Paperclip Council",
  description: "Private Council integration with revisioned rosters, bounded admission and checked candidate preparation.",
  author: "Local Paperclip integration",
  categories: ["automation"],
  capabilities: [
    "api.routes.register",
    "companies.read",
    "projects.read",
    "agents.read",
    "database.namespace.migrate",
    "database.namespace.read",
    "database.namespace.write",
    "issues.read",
    "issues.create",
    "issues.update",
    "issues.checkout",
    "issues.wakeup",
    "issues.orchestration.read",
    "issue.documents.read",
    "issue.attachments.read",
    "issue.interactions.create",
    "issue.interactions.read",
    "issue.interactions.respond",
    "secrets.read-ref",
    "ui.page.register",
  ],
  entrypoints: { worker: "./dist/worker.js", ui: "./dist/ui" },
  database: {
    namespaceSlug: "private_paperclip_council",
    migrationsDir: "migrations",
    coreReadTables: ["companies", "issues", "projects"],
  },
  instanceConfigSchema: {
    type: "object",
    additionalProperties: false,
    required: ["apiBaseUrl", "councilAgentId", "councilApiKey"],
    properties: {
      apiBaseUrl: {
        type: "string",
        format: "uri",
        title: "Paperclip API base URL",
        description: "Loopback origin of the Paperclip instance, without credentials, path, query, fragment, or an /api suffix.",
      },
      councilAgentId: {
        type: "string",
        format: "uuid",
        title: "Council agent ID",
        description: "Paperclip agent whose dedicated standard API key is stored below.",
      },
      councilApiKey: {
        format: "secret-ref",
        title: "Council agent API key",
        description: "Reference to the Paperclip company secret containing the dedicated council agent token.",
      },
      n1FixtureMode: {
        type: "string",
        enum: ["ephemeral-local-sandbox"],
        title: "N1 test fixture mode",
        description: "Only for the repo-owned ephemeral test host; real admission remains unqualified.",
      },
      n1OperatingProfile: {
        type: "object",
        additionalProperties: false,
        required: [
          "kind", "periodKey", "periodStart", "periodEnd", "periodAllowanceUnits", "runReservationUnits",
          "initialKnownUsageUnits", "initialExposureUnits", "initialTokenAccountingSource",
        ],
        title: "N1 bounded operating profile",
        description: "One native token-ledger profile for sequential N1 contribution runs.",
        properties: {
          kind: { type: "string", enum: ["paperclip-orchestration-tokens-v1"] },
          periodKey: { type: "string", minLength: 1, maxLength: 200 },
          periodStart: { type: "string", format: "date-time" },
          periodEnd: { type: "string", format: "date-time" },
          periodAllowanceUnits: { type: "integer", minimum: 1 },
          runReservationUnits: { type: "integer", minimum: 1 },
          initialKnownUsageUnits: { type: "integer", minimum: 0 },
          initialExposureUnits: { type: "integer", minimum: 0 },
          initialTokenAccountingSource: { type: "string", minLength: 1, maxLength: 200 },
        },
      },
    },
  },
  apiRoutes: [
    {
      routeKey: "admission-read",
      method: "GET",
      path: "/companies/:companyId/admission",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "admission-command",
      method: "POST",
      path: "/companies/:companyId/admission",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "mission-agent-command",
      method: "POST",
      path: "/issues/:issueId/council/commands",
      auth: "agent",
      capability: "api.routes.register",
      checkoutPolicy: "required-for-agent-in-progress",
      companyResolution: { from: "issue", param: "issueId" },
    },
    {
      routeKey: "rosters-list",
      method: "GET",
      path: "/companies/:companyId/rosters",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "rosters-command",
      method: "POST",
      path: "/companies/:companyId/rosters",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "roster-read",
      method: "GET",
      path: "/companies/:companyId/rosters/:rosterId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "roster-command",
      method: "POST",
      path: "/companies/:companyId/rosters/:rosterId/commands",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "missions-list",
      method: "GET",
      path: "/companies/:companyId/missions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "missions-command",
      method: "POST",
      path: "/companies/:companyId/missions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "mission-read",
      method: "GET",
      path: "/companies/:companyId/missions/:missionId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "mission-command",
      method: "POST",
      path: "/companies/:companyId/missions/:missionId/commands",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "decision",
      method: "POST",
      path: "/issues/:issueId/decision",
      auth: "agent",
      capability: "api.routes.register",
      checkoutPolicy: "required-for-agent-in-progress",
      companyResolution: { from: "issue", param: "issueId" },
    },
    {
      routeKey: "council-decisions-list",
      method: "GET",
      path: "/companies/:companyId/decisions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "council-decision-human",
      method: "POST",
      path: "/companies/:companyId/decisions/human",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "foundation-probe",
      method: "POST",
      path: "/issues/:issueId/foundation-probe",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "issue", param: "issueId" },
    },
  ],
  ui: {
    slots: [{
      type: "page",
      id: "council-rosters",
      displayName: "Council rosters",
      exportName: "CouncilRostersPage",
      routePath: "council-rosters",
    }, {
      type: "page",
      id: "council-missions",
      displayName: "Council missions",
      exportName: "CouncilMissionsPage",
      routePath: "council-missions",
    }],
  },
};

export default manifest;
