import type { MissionRecord } from "./missions.js";
import type { OrdinaryTask } from "./n2-ordinary-state.js";

/** Complete installed command contract, also returned by inspect for the root correction. */
export function ordinaryTaskInstructions(mission: MissionRecord, task: OrdinaryTask): string {
  return `Council ordinary CLI task ${task.taskId}; missionId=${mission.missionId}; role=${task.kind}.
Use your own PAPERCLIP_API_URL, PAPERCLIP_API_KEY, PAPERCLIP_RUN_ID and PAPERCLIP_AGENT_ID. Never print credentials.
Read your assigned issue at GET /api/issues/$PAPERCLIP_TASK_ID for companyId/projectId. Authenticate with Authorization: Bearer $PAPERCLIP_API_KEY and X-Paperclip-Run-Id: $PAPERCLIP_RUN_ID.
POST /api/plugins/private.paperclip-council/api/issues/$PAPERCLIP_TASK_ID/council/commands with JSON {"missionId":"${mission.missionId}","command":"ordinary-inspect"}. This agent-authenticated plugin API is the ordinary CLI route. Check the HTTP status and read its JSON response. Do not assume the separate plugin tool gateway is authorized; a 403 there does not authorize a bypass or policy change.
For every mutation first inspect; body={missionId,command,commandId,expectedVersion,...payload}. Generate a fresh UUID (node:crypto.randomUUID) for each logical command; expectedVersion is inspect.version. If its response is uncertain, replay the IDENTICAL body/key, never invent a replacement command. Actor/run attribution comes from authentication, never from model-supplied body fields.
Inspection supplies task, n2.submission, n3.review and rootIssueId. Preserve the exact subject tuple from n3.review.subject. Evidence or candidate changes require a new review. No implicit agreement from task completion.
${task.kind === "specialist" ? `Submit command=n3-opinion with opinion={opinionId:<UUID>,slotId:task.slotId,subject:n3.review.subject,outcome:"support"|"changes_requested"|"insufficient_evidence",rationale:<reason>,findings:[{findingId:<UUID>,classification:"blocking_defect"|"decisive_uncertainty"|"deferrable_improvement",criterionOrRisk,evidenceRefs:[...],evidenceLimits:[...],consequence,recommendedAction}],unresolvedQuestions:[...]}. Inspect the exact candidate and your slot question; do not alter Git or issue a final verdict.`
    : task.kind === "council" ? `Read every opinion in ONLY the current n3.review round and its unresolved questions. Council alone submits command=ordinary-verdict with synthesis={subject:n3.review.subject,verdict:"approved"|"changes_requested",rationale:<reasoned judgment>,dispositions:[{findingId,disposition:"upheld_with_correction"|"resolved_by_evidence"|"rejected_with_reason"|"escalated",reason,evidenceRefs:[...]}]}. Dispositions cover exactly the current round findings classified blocking_defect or decisive_uncertainty. Exclude deferrable_improvement findings and every historical round finding; use dispositions:[] when the current round has no material findings. The rationale may discuss verified historical fixes. Unresolved decisive evidence blocks approval. Finish your CLI response with ONLY the exact returned finishReport JSON (no markdown or extra prose). Persisting this report does not yet apply it: terminal run and per_run usage must settle first.`
    : `Read n2.correction.criteria/reasons and the Council synthesis. ${mission.aggregate.n5?.continuation ? "For this post-publication correction, first ordinary-inspect binds the owner resumed root run. Update the existing root plan document with its baseRevisionId while preserving mandate/roles, then call n5-rebind-plan with commandId, expectedVersion, new planRevisionId and reason before preparing V2." : "This correction is before publication: preserve the existing plan document and its owner-bound revision. Do not rewrite the plan or call n5-rebind-plan; neither is a prerequisite for V2."} Perform only the admitted correction. Preserve base and the ${mission.aggregate.hierarchy ? "pinned" : "two attributed"} contribution commits; AMEND the single integration commit (git commit --amend), producing a new candidate SHA, rather than adding a second candidate-only commit. Create a self-contained Git bundle with refs/heads/base and refs/heads/candidate. POST multipart file to /api/companies/<companyId>/issues/${mission.rootIssueId}/attachments; compute its SHA-256. Submit command=prepare-resubmission with attachmentId,baseCommit,candidateCommit,expectedSha256,submissionId:<new UUID>,correctedPaths:[<actually changed attributed paths>]. correctedPaths contains only material changes within the ${mission.aggregate.hierarchy ? "pinned" : "two"} contribution ownedPaths; keep existing integrationAdjustedPaths separate and do not declare README/report integration-only paths there. This verifies V2; it does not accept it.`}
After your successful submission, the plugin records blocked: waiting for this run's terminal usage and the next Council stage. Finish normally. Never PATCH done, reassign, create dependent tasks, trigger a wake, or enter native in_review. Only the installed controller admits the next task after public terminal/usage readback. On refusal or unknown effect, retain identity and exposure and report the exact blocker; no blind retry.`;
}
