import type { MissionRecord } from "./missions.js";

export function n5PublisherInstructions(mission: MissionRecord): string {
  return `Mission ${mission.missionId}. Use n5-inspect then n5-claim-publication before any git/gh effect.
For ordinary-cli-v1 use POST /api/plugins/private.paperclip-council/api/issues/$PAPERCLIP_TASK_ID/council/commands at your PAPERCLIP_API_URL, Authorization: Bearer $PAPERCLIP_API_KEY and X-Paperclip-Run-Id: $PAPERCLIP_RUN_ID. Body {missionId:"${mission.missionId}",command:"n5-inspect"}. Read version and delivery.publication/authority. Mutations add commandId (fresh crypto.randomUUID per logical operation) and expectedVersion from fresh inspection. Unknown response: replay identical body/key, never a new effect key. Do not assume plugin tool gateway permission.
Only n5-claim-publication returning effectPermission=execute permits one effect. Before git/gh, verify local and remote candidate/ref against publication.submission and authority. operation=create permits one PR; operation=update permits updating ONLY the existing targetUrl PR and unchanged authorized branch to the newly accepted head. Never create another PR for an update, and never repeat an uncertain publication effect.
Record the effect through POST /api/issues/$PAPERCLIP_TASK_ID/work-products with {type:"pull_request",provider:"github",title,url,createdByRunId:<own run>}; PUT /api/issues/$PAPERCLIP_TASK_ID/documents/delivery with {format:"markdown",title,body:JSON.stringify({intentId:publication.intentId,url,link:"<"+url+">"})}. Keep the canonical same URL. Then GET external-objects and POST external-objects/refresh on this issue with {objectIds:[<matching GitHub object ID>]}.
Call n5-observe-delivery with a fresh version/key after refresh. Optional checks={headSha,state:"unknown"|"pending"|"passed"|"failed",evidenceRefs:[...]}, reviews={headSha,state:"unknown"|"pending"|"approved"|"changes_requested",evidenceRefs:[...]}; state and evidence must be attributable to this exact head. Never invent checks or approvals.
A cached old snapshot/backoff cannot attest an update. Preserve the one-shot intent and report its object ID/nextRefreshAt; finish normally. After refresh becomes eligible, the owner can refresh via the same public issue API and reconcile-delivery with exact-head observations, without another model run or GitHub effect.
On ordinary missions the plugin records blocked while the admitted run/effect awaits terminal accounting/readback, then closes only after terminal settlement. Do not PATCH done, reassign, resume or trigger another wake yourself. Finishing alone is neither publication readback nor delivery readiness. Historical runner missions retain their existing authorized tool surface. No merge or deployment is included.`;
}
