import { cancellationInstructions } from "./linear-cancellation-instructions.js";
import { integrationInstructions } from "./integration-instructions.js";
import type { MissionRecord } from "./missions.js";
import { fileURLToPath } from "node:url";
import { projectRoleContext } from "./project-workflow.js";

export function n5PublisherInstructions(mission: MissionRecord): string {
  if (mission.aggregate.n5?.publication?.operation === "cancel-pr") return cancellationInstructions(mission);
  if (mission.aggregate.n5?.publication?.operation === "integrate") return integrationInstructions(mission);
  const preflight = mission.aggregate.n5?.authority.publisherPreflight ? `
Before n5-claim-publication, run the Council read-only preflight in YOUR current native publisher environment. Use python3 with the argv vector [${JSON.stringify(fileURLToPath(new URL("../scripts/operations/publisher_preflight.py", import.meta.url)))}, "--repo", <absolute current repository root>, "--repository", authority.repository, "--candidate", publication.submission.candidateCommit, "--base-ref", authority.baseRef, "--base-sha", publication.submission.baseCommit, "--head-ref", authority.headRef, "--mission-id", "${mission.missionId}", "--intent-id", publication.intentId]. For operation=update also add ["--expected-remote-head", delivery.continuation.previousPublication.submission.candidateCommit]. Do not interpolate unquoted shell text. It inherits your native GitHub projection and reads PAPERCLIP_TASK_ID/PAPERCLIP_RUN_ID; do not add an operator token, copy credentials, change access policies or run another model.
This preflight only reads Git/GitHub. Its report must have status=pass; include that exact parsed JSON as preflight in the n5-claim-publication body. Missing/stale/foreign/refused reports grant no publication write. On refusal, report the bounded reason and finish without a push, PR or blind retry; this already admitted publisher run still consumes its normal admission/usage. Do not infer actual push success from permissions.push or a read-only report. Council stores publisher_run_report provenance, separately from subsequent native publication readback.
` : "";
  const contract = mission.aggregate.n5?.authority.contract;
  const contractGuidance = contract ? `Explicit PR contract: ${JSON.stringify(contract)}. For operation=create run gh pr create with fixed argv --repo authority.repository --base authority.baseRef --head authority.headRef, a bounded title/body, and ${contract.draftOnly ? "--draft" : "the authorized non-draft state"}. Preserve this state for update; never call gh pr ready or merge. Native readback rejects a draft-state violation.
After the native object resolves this exact candidate, run python3 with argv [${JSON.stringify(fileURLToPath(new URL("../scripts/operations/github_feedback.py", import.meta.url)))}, "--url", <canonical same PR>, "--repository", authority.repository, "--head", publication.submission.candidateCommit, "--mission-id", "${mission.missionId}", "--intent-id", publication.intentId] in YOUR current admitted environment. Include the entire parsed JSON as feedbackReport in n5-observe-delivery; Council derives CI/review states, not supplied booleans. Reports are attributed actor evidence. Read refusal, pagination overflow, changed cohort or unknown publication outcome stops the run without another effect.
For a cached old head, remain in this already admitted publisher run only while its original deadline/admission allow a bounded wait, maximum 305 seconds. Read nextRefreshAt and wait until eligible, then refresh the matching native object once and inspect it. No new model run, operator credential or alternate key is authorized. A still old/unknown object stops with the retained intent. Fetch feedback only after exact-head native resolution so its observation is fresh. CHANGES_REQUESTED with green CI cannot be delivery-ready or merge-ready; the durable Council controller owns independent feedback review and the existing single correction.
` : "";
  const context = projectRoleContext(mission, "publisher");
  return `${context ? `${context}\n\n` : ""}Mission ${mission.missionId}. Use n5-inspect then n5-claim-publication before any publication write.
For ordinary-cli-v1 use POST /api/plugins/private.paperclip-council/api/issues/$PAPERCLIP_TASK_ID/council/commands at your PAPERCLIP_API_URL, Authorization: Bearer $PAPERCLIP_API_KEY and X-Paperclip-Run-Id: $PAPERCLIP_RUN_ID. Body {missionId:"${mission.missionId}",command:"n5-inspect"}. Read version and delivery.publication/authority. Mutations add commandId (fresh crypto.randomUUID per logical operation) and expectedVersion from fresh inspection. Unknown response: replay identical body/key, never a new effect key. Do not assume plugin tool gateway permission.
${preflight}${contractGuidance}Only n5-claim-publication returning effectPermission=execute permits one publication effect. Read-only prerequisite checks are allowed before that claim. Verify local and remote candidate/ref against publication.submission and authority. operation=create permits one PR; operation=update permits updating ONLY the existing targetUrl PR and unchanged authorized branch to the newly accepted head. Never create another PR for an update, and never repeat an uncertain publication effect.
For create, first confirm the authorized remote head does not exist; push the exact accepted commit with an empty explicit lease: git push --force-with-lease=refs/heads/<head>: origin <acceptedV1>:refs/heads/<head>. For update, read oldV1 from delivery.continuation.previousPublication.submission.candidateCommit and its observed head; require both agree, remote refs/heads/<head> still equals oldV1 and local HEAD equals acceptedV2. Because correction amends the integration commit, use git push --force-with-lease=refs/heads/<head>:<oldV1> origin <acceptedV2>:refs/heads/<head>. Never use blind --force or an implicit tracking-ref lease. A mismatched/refused lease is a stop, not permission to retry against a different old head. Read back remote V2 and the same PR URL before recording the effect. Inspect the persisted intent first; a claim replay never grants a second push/create.
Record the effect through POST /api/issues/$PAPERCLIP_TASK_ID/work-products with {type:"pull_request",provider:"github",title,url,createdByRunId:<own run>}; PUT /api/issues/$PAPERCLIP_TASK_ID/documents/delivery with {format:"markdown",title,body:JSON.stringify({intentId:publication.intentId,url,link:"<"+url+">"})}. Keep the canonical same URL. Then GET external-objects and POST external-objects/refresh on this issue with {objectIds:[<matching GitHub object ID>]}.
Call n5-observe-delivery with a fresh version/key after refresh. Optional checks={headSha,state:"unknown"|"pending"|"passed"|"failed",evidenceRefs:[...]}, reviews={headSha,state:"unknown"|"pending"|"approved"|"changes_requested",evidenceRefs:[...]}; state and evidence must be attributable to this exact head. Never invent checks or approvals.
Plugins/skills à utiliser: installed Council delivery contract, then repository Git/GitHub guidance. Modèle et effort recommandés: bounded publisher, gpt-5.6-sol medium; mapping ~/.codex/shared/model-selection/model-effort-mapping.md dated 2026-09-05, reassess only on material unresolved evidence. This is advisory; the pinned native profile and runtime readback determine effective settings, availability unverified here.
A cached old snapshot/backoff cannot attest an update. Preserve the one-shot intent and report its object ID/nextRefreshAt; finish normally. After refresh becomes eligible, the owner can refresh via the same public issue API and reconcile-delivery with exact-head observations, without another model run or GitHub effect.
On ordinary missions the plugin records blocked while the admitted run/effect awaits terminal accounting/readback, then closes only after terminal settlement. Do not PATCH done, reassign, resume or trigger another wake yourself. Finishing alone is neither publication readback nor delivery readiness. Historical runner missions retain their existing authorized tool surface. No merge or deployment is included.`;
}
